### ISSUE TITLE
Server -> Client Events?

### ISSUE THREAD

**Issue by boxxa** [raix/Meteor-EventEmitter#11]
Is ist possible to emit an event from the server and process it on the client? I am trying below. I have a setInterval running on my server to emit the number data to the client but doesn't seem to work. If I move my server code to the client it works perfectly. Not sure if this is possible or out of the scope of this package.

**server.js**
`Meteor.startup(function(){
  Event = new EventEmitter();
  Meteor.setInterval(function(){
    console.log("Emitting")
    Event.emit('game-spin', {
    number: 6
    })
  },2000);
})`

**client.js**
`var listener;
Meteor.startup(function(){
  Event = new EventEmitter();
})
Template.gamePartial.onCreated(function() {
    listener = function(data) {
        console.log('Listening custom event', data);
    };
    Event.on('game-spin', listener);
})
Template.gamePartial.onDestroyed(function() {
    Event.removeListener('game-spin', listener);
})
`

**Comment by boxxa** [comment]
Closing. Found your eventddp package which does this perfectly.

https://atmospherejs.com/raix/eventddp

**Comment by raix** [comment]
:)
