### ISSUE TITLE
emit from server to client/ or vice versa

### ISSUE THREAD

**Issue by babnik63** [raix/Meteor-EventEmitter#4]
Hi,
Does it supports emitting an event from server to client and from client to server?

**Comment by raix** [comment]
nope this is a plain / tiny eventemitter - but we have been talking about client/server event handling on the cfs team

**Comment by almogdesign** [comment]
+1 it would be nice to have that

**Comment by dcworldwide** [comment]
+1 that would be very useful

**Comment by raix** [comment]
I'm closing this issue - please subscribe to: https://github.com/raix/Meteor-EventDDP
