### ISSUE TITLE
Why not just use Tracker?

### ISSUE THREAD

**Issue by ccorcos** [raix/Meteor-EventEmitter#5]
It seems to me like wrapping a reactive variable in a Tracker.autorun accomplishes the exact same thing as an event emitter but with more declarative syntax as opposed to imperative syntax... Just curious when you'd want to use an event emitter as opposed to a reactive variable?

**Comment by raix** [comment]
Tracker is for tracking variables, eventemitter is emitting event specific data.
Question is: why not use obsevable streams?
I dont think theres yet "one ring to rule em all"

**Comment by ccorcos** [comment]
observable streams?!

**Comment by raix** [comment]
https://www.youtube.com/watch?v=XRYN2xt11Ek

**Comment by ccorcos** [comment]
Whoa! That is a very good point! Observables looks awesome! 

The question for me now is where does this fit in to meteor? I could see this being a very useful way of dealing with events. Something like this:

```
streams = (events) ->
  for e in events
    t = Template.instance()
    t[e] = (elem) -> 
      @elem = t.find(elem)
      Rx.Observable.fromEvent(@elem, e)
   
Template.main.created = ->
  streams('mousedown', 'mouseup', 'mousemove')

Template.main.rendered = ->
  t = @
  t.mousedown('.image')
    .map((down) -> t.mousemove.takeUntil(t.mouseUp))
    .concatAll()
    .forEach((pos) -> @elem.position = pos)
```

It would be really cool if meteor had something like `Template.eventStreams` for all this stuff. I'm still not entirely sure how all this works though. Do you have to manually turn every event into a stream or does it automatically do that for you? For example, [he just calls `elmt.mouseDowns` and `document.mouseMoves` without defining those streams...](http://youtu.be/XRYN2xt11Ek?t=20m16s).

I'm trying to think of when or where you'd use this for a collection. The Mongo cursor with reactive session variables seems to take care of search pretty easily, but then again, I think observable streams would be better if helpers can accept them because you don't have to wire in event listeners and session variables.

The meteor way:

```
Session.set('search', '')

Template.main.events
  'keyup input':(e,t) -> Session.set('search', e.target.value)

Template.main.helpers
  results: -> Items.find({name:Session.get('search')})

```

The observable way:

```
Template.main.helpers
  results: ->
    t = Template.instance()
    t.keyPresses.throttle(250)
      .map((key) -> Items.find({name:t.find('input')))
      .concatAll()
```

This is pretty messy and probably incorrect, but I think theres something to this... Thanks for sharing that video. Very cool stuff.

**Comment by rhyslbw** [comment]
+1 on the video, well worth the watch.

I'm also quite new to these concepts here, but isn't the combination of Tracker, reactive vars, and pub/sub (?) implementing an observer pattern? The upcoming changes to Blaze formalises instance reactive variables to manage state outside of the Session object, and template level subscriptions, so it seems that creating a reactive var for keyPresses in Template.main.created with jQuery selectors updating it would achieve what you have outlined in 'The observable way' right?  

https://medium.com/@stubailo/upcoming-features-in-meteor-blaze-b537cf9c09e9

**Comment by ccorcos** [comment]
Thanks for the article. I like those updates, but I'm ready for those already and [more!](https://github.com/meteor/meteor/issues/3650)

It is my understanding that you're entirely right -- Tracker and Observable Streams are the exact same underlying concept implemented slightly differently. Tracker maintains a graph of function dependency relationships using autorun while observable streams manage these dependencies by treating reactive variables as async-arrays. 

Tracker is amazing and transparent. But I think there are certain things that observables seem to do better. Making a dom element draggable or typeahead are perfect examples. A common pattern in meteor is to have a helper that depends on a reactive variable and an event to update that variable. I think this pattern can be consolidated into a single helper with an observable stream. 

For a simple template, the reactive variable pattern is simple and awesome. But given a complicated template, we can offload the internal state into a very functional observable stream pattern.

**Comment by rhyslbw** [comment]
Just to ensure we are comparing with the upcoming version of Blaze, you will be able to access the local template state directly in the template without the need for a helper

    Template.calendar.onCreated(function () {
        // Declare some temporary state
        this.vars.setDefault("selectedDay", new Date());
        this.vars.setDefault("viewStyle", “month”);
    });
    // No need to define helpers, just use
    // {{Template.vars.selectedDay}}

I'm probably not seeing this properly, but where would you map an interaction event to a stream if it's not the responsibility out of the template events map?

**Comment by ccorcos** [comment]
[Check out this nightmare](https://github.com/ccorcos/meteor-swipe/blob/master/swipe/swipe.coffee#L332) for an example of how big a hassle it is to manage event state for swiping.

The typeahead is an interesting scenario as well. The current way of doing it is like this:

```
Session.set('search', '')

Template.main.events
  'keyup input':(e,t) -> Session.set('search', e.target.value)

Template.main.helpers
  results: -> Items.find({name:Session.get('search')})
```

With Template.vars we can eliminate the first line, but its the same idea. We have a helper and an event.

The observable way looks something like this:

```
Template.main.helpers
  results: ->
    input = t.find('input')
    input.keyPresses.throttle(250)
      .map((key) -> Items.find({name:input.value).fetch())
      .concatAll()
```

Now that doesnt look like a big difference, but the tiny amounts of state you need to keep track of can pile up as you can see in my "nightmare" link. Suppose you have a more complicated template with many helpers and many events and many Template.vars. If you see a helper that depends on some Template.var, its a pain to look around at which events alter that Template.var. In the observable example, everything is right there and you don't have to go searching for all the pieces.

My point here is just that there are certain things that would be much easier with observables as opposed to Template.vars and vice-versa. These are just two examples where I think observable streams are better.

**Comment by ccorcos** [comment]
@raix thanks for showing me that video!

https://github.com/ccorcos/meteor-tracker-streams

**Comment by raix** [comment]
@ccorcos no problem, nice work :)

**Comment by rhyslbw** [comment]
Thanks @ccorcos. Your package will be a big help in understanding the difference now.

**Comment by ccorcos** [comment]
@rhyslbw I hope you like it :)
