### ISSUE TITLE
Add feature: `emitState`

### ISSUE THREAD

**Issue by raix** [raix/Meteor-EventEmitter#9]
We lack an emitter to simulate a `state` an example could be the cordova ready event where we want to be notified when a state changes, if a state is already set we will run the listener at registration.

Another use case is for the `raix:push` package where a push message can be set before Meteor is even ready/after ready etc. So the message can be interpreted as a state, eg. we want to get the state and updates.

cc: @arunoda *(If you have input or opinion about this)*

**Comment by arunoda** [comment]
I'm not familiar with cordova and frankly didn't get what you've said.
How about some code example?

**Comment by raix** [comment]
:) fair enough

```js
  var em = new EventEmitter();


  em.addListener('ready', function() {
    // I'm waiting on the ready state
  });

  // Emit a ready state - additional data is optional
  em.emitState('ready');

  em.addListener('ready', function() {
    // I'll just run since the ready state is already triggered
  });  
```

**Comment by arunoda** [comment]
Okay. got it.
Then I think, it's better we build it as a separate package.

I know, it can be useful for a lot of places. For example, when creating
ready callbacks and so on.

May be you can use this package behind the scene.

**Comment by raix** [comment]
yep, good point - might be best to keep this package as clean as possible - maybe I'll add a eventState package instead, thanks!
